# Import pywal colors
[general]
import = ["~/.cache/wal/alacritty.toml"]

[window]
padding = { x = 12, y = 12 }
opacity = 0.8
dynamic_title = true


[font]
# Point size
size = 17.0 # <-- Adjust this number for your preferred size

# Normal (Regular) font face
[font.normal]
# Use the exact family name from fc-list
family = "Iosevka Nerd Font"
style = "Regular" # Usually not needed if family name is specific

# Bold font face
[font.bold]
# Alacritty should find this automatically if 'normal.family' is set,
# but you can specify explicitly if needed.
family = "Iosevka Nerd Font"
style = "Bold"

# Italic font face
[font.italic]
# Alacritty should find this automatically if 'normal.family' is set,
# but you can specify explicitly if needed.
family = "Iosevka Nerd Font"
style = "Italic"

# Bold Italic font face
[font.bold_italic]
# Alacritty should find this automatically if 'normal.family' is set,
# but you can specify explicitly if needed.
family = "Iosevka Nerd Font"
style = "Bold Italic"

[cursor]
style = "Beam"
vi_mode_style = "Block"
blink_interval = 750
unfocused_hollow = true
thickness = 0.15
